version: '3'

services:

  defi-dog:
    build: .
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-Dconfig.file=/app/config/application-prod.properties", "-jar", "defi-dog.jar"]
    volumes:
      - './src/main/resources/application-prod.properties:/app/config/application-prod.properties'
    restart: always
    container_name: defi-dog
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - PG_DATASOURCE_URL=jdbc:postgresql://defi-dog-db:5432/defidog
      - PG_NAME=pgadmin
      - PG_PASS=pgadmin
    tty: true
    depends_on:
      - defi-dog-db

  defi-dog-db:
    build:
      dockerfile: ./Dockerfile
      context: postgres
    restart: always
    container_name: defi-dog-db
    ports:
      - "25434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "kuramshin.py@yandex.ru"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5052:80"
    depends_on:
      - defi-dog-db

volumes:
  postgres_data:
  pgadmin_data:
    driver: local