/*
 * Sourcify APIv2
 * Welcome to the Sourcify's APIv2.  Important differences between the deprecated legacy API and the new APIv2: - **Ticketing**: The verfication requests resolve into tickets/verification jobs.    - Previously the verification happened during the HTTP request, which resulted in timeouts if compilation took longer - **Standard JSON as default**: In the current design we take the standard JSON format as our main verification endpoint. We still support verification with metadata at `/v2/verify/metadata`. - **Lean API**: We keep the number of endpoints minimal compared to v1. We won't have a session API.  - **Detailed contract response**: Prev. we only returned contract files of a contract. Now we can return details at `/contract/{chainId}/{address}`.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@sourcify.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.javaboys.defidog.integrations.sourcify.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * CreationBytecodeResponse
 */
@JsonPropertyOrder({
  CreationBytecodeResponse.JSON_PROPERTY_ONCHAIN_BYTECODE,
  CreationBytecodeResponse.JSON_PROPERTY_RECOMPILED_BYTECODE,
  CreationBytecodeResponse.JSON_PROPERTY_SOURCE_MAP,
  CreationBytecodeResponse.JSON_PROPERTY_LINK_REFERENCES,
  CreationBytecodeResponse.JSON_PROPERTY_CBOR_AUXDATA,
  CreationBytecodeResponse.JSON_PROPERTY_TRANSFORMATIONS,
  CreationBytecodeResponse.JSON_PROPERTY_TRANSFORMATION_VALUES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-08T01:55:37.009934+03:00[Europe/Moscow]", comments = "Generator version: 7.7.0")
public class CreationBytecodeResponse {
  public static final String JSON_PROPERTY_ONCHAIN_BYTECODE = "onchainBytecode";
  private String onchainBytecode;

  public static final String JSON_PROPERTY_RECOMPILED_BYTECODE = "recompiledBytecode";
  private String recompiledBytecode;

  public static final String JSON_PROPERTY_SOURCE_MAP = "sourceMap";
  private String sourceMap;

  public static final String JSON_PROPERTY_LINK_REFERENCES = "linkReferences";
  private LinkReferences linkReferences;

  public static final String JSON_PROPERTY_CBOR_AUXDATA = "cborAuxdata";
  private Map<String, CborAuxdataObject> cborAuxdata = new HashMap<>();

  public static final String JSON_PROPERTY_TRANSFORMATIONS = "transformations";
  private List<CreationBytecodeResponseTransformationsInner> transformations = new ArrayList<>();

  public static final String JSON_PROPERTY_TRANSFORMATION_VALUES = "transformationValues";
  private CreationTransformationValues transformationValues;

  public CreationBytecodeResponse() {
  }

  public CreationBytecodeResponse onchainBytecode(String onchainBytecode) {
    
    this.onchainBytecode = onchainBytecode;
    return this;
  }

  /**
   * Get onchainBytecode
   * @return onchainBytecode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ONCHAIN_BYTECODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOnchainBytecode() {
    return onchainBytecode;
  }


  @JsonProperty(JSON_PROPERTY_ONCHAIN_BYTECODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOnchainBytecode(String onchainBytecode) {
    this.onchainBytecode = onchainBytecode;
  }

  public CreationBytecodeResponse recompiledBytecode(String recompiledBytecode) {
    
    this.recompiledBytecode = recompiledBytecode;
    return this;
  }

  /**
   * Get recompiledBytecode
   * @return recompiledBytecode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RECOMPILED_BYTECODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRecompiledBytecode() {
    return recompiledBytecode;
  }


  @JsonProperty(JSON_PROPERTY_RECOMPILED_BYTECODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRecompiledBytecode(String recompiledBytecode) {
    this.recompiledBytecode = recompiledBytecode;
  }

  public CreationBytecodeResponse sourceMap(String sourceMap) {
    
    this.sourceMap = sourceMap;
    return this;
  }

  /**
   * Get sourceMap
   * @return sourceMap
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE_MAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSourceMap() {
    return sourceMap;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_MAP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceMap(String sourceMap) {
    this.sourceMap = sourceMap;
  }

  public CreationBytecodeResponse linkReferences(LinkReferences linkReferences) {
    
    this.linkReferences = linkReferences;
    return this;
  }

  /**
   * Get linkReferences
   * @return linkReferences
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LINK_REFERENCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public LinkReferences getLinkReferences() {
    return linkReferences;
  }


  @JsonProperty(JSON_PROPERTY_LINK_REFERENCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLinkReferences(LinkReferences linkReferences) {
    this.linkReferences = linkReferences;
  }

  public CreationBytecodeResponse cborAuxdata(Map<String, CborAuxdataObject> cborAuxdata) {
    
    this.cborAuxdata = cborAuxdata;
    return this;
  }

  public CreationBytecodeResponse putCborAuxdataItem(String key, CborAuxdataObject cborAuxdataItem) {
    if (this.cborAuxdata == null) {
      this.cborAuxdata = new HashMap<>();
    }
    this.cborAuxdata.put(key, cborAuxdataItem);
    return this;
  }

  /**
   * Get cborAuxdata
   * @return cborAuxdata
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CBOR_AUXDATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, CborAuxdataObject> getCborAuxdata() {
    return cborAuxdata;
  }


  @JsonProperty(JSON_PROPERTY_CBOR_AUXDATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCborAuxdata(Map<String, CborAuxdataObject> cborAuxdata) {
    this.cborAuxdata = cborAuxdata;
  }

  public CreationBytecodeResponse transformations(List<CreationBytecodeResponseTransformationsInner> transformations) {
    
    this.transformations = transformations;
    return this;
  }

  public CreationBytecodeResponse addTransformationsItem(CreationBytecodeResponseTransformationsInner transformationsItem) {
    if (this.transformations == null) {
      this.transformations = new ArrayList<>();
    }
    this.transformations.add(transformationsItem);
    return this;
  }

  /**
   * Get transformations
   * @return transformations
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSFORMATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<CreationBytecodeResponseTransformationsInner> getTransformations() {
    return transformations;
  }


  @JsonProperty(JSON_PROPERTY_TRANSFORMATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransformations(List<CreationBytecodeResponseTransformationsInner> transformations) {
    this.transformations = transformations;
  }

  public CreationBytecodeResponse transformationValues(CreationTransformationValues transformationValues) {
    
    this.transformationValues = transformationValues;
    return this;
  }

  /**
   * Get transformationValues
   * @return transformationValues
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRANSFORMATION_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreationTransformationValues getTransformationValues() {
    return transformationValues;
  }


  @JsonProperty(JSON_PROPERTY_TRANSFORMATION_VALUES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTransformationValues(CreationTransformationValues transformationValues) {
    this.transformationValues = transformationValues;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreationBytecodeResponse creationBytecodeResponse = (CreationBytecodeResponse) o;
    return Objects.equals(this.onchainBytecode, creationBytecodeResponse.onchainBytecode) &&
        Objects.equals(this.recompiledBytecode, creationBytecodeResponse.recompiledBytecode) &&
        Objects.equals(this.sourceMap, creationBytecodeResponse.sourceMap) &&
        Objects.equals(this.linkReferences, creationBytecodeResponse.linkReferences) &&
        Objects.equals(this.cborAuxdata, creationBytecodeResponse.cborAuxdata) &&
        Objects.equals(this.transformations, creationBytecodeResponse.transformations) &&
        Objects.equals(this.transformationValues, creationBytecodeResponse.transformationValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(onchainBytecode, recompiledBytecode, sourceMap, linkReferences, cborAuxdata, transformations, transformationValues);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreationBytecodeResponse {\n");
    sb.append("    onchainBytecode: ").append(toIndentedString(onchainBytecode)).append("\n");
    sb.append("    recompiledBytecode: ").append(toIndentedString(recompiledBytecode)).append("\n");
    sb.append("    sourceMap: ").append(toIndentedString(sourceMap)).append("\n");
    sb.append("    linkReferences: ").append(toIndentedString(linkReferences)).append("\n");
    sb.append("    cborAuxdata: ").append(toIndentedString(cborAuxdata)).append("\n");
    sb.append("    transformations: ").append(toIndentedString(transformations)).append("\n");
    sb.append("    transformationValues: ").append(toIndentedString(transformationValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

