/*
 * Sourcify APIv2
 * Welcome to the Sourcify's APIv2.  Important differences between the deprecated legacy API and the new APIv2: - **Ticketing**: The verfication requests resolve into tickets/verification jobs.    - Previously the verification happened during the HTTP request, which resulted in timeouts if compilation took longer - **Standard JSON as default**: In the current design we take the standard JSON format as our main verification endpoint. We still support verification with metadata at `/v2/verify/metadata`. - **Lean API**: We keep the number of endpoints minimal compared to v1. We won't have a session API.  - **Detailed contract response**: Prev. we only returned contract files of a contract. Now we can return details at `/contract/{chainId}/{address}`.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@sourcify.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.javaboys.defidog.integrations.sourcify.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * GetContract200Response
 */
@JsonPropertyOrder({
  GetContract200Response.JSON_PROPERTY_MATCH,
  GetContract200Response.JSON_PROPERTY_CREATION_MATCH,
  GetContract200Response.JSON_PROPERTY_RUNTIME_MATCH,
  GetContract200Response.JSON_PROPERTY_CHAIN_ID,
  GetContract200Response.JSON_PROPERTY_ADDRESS,
  GetContract200Response.JSON_PROPERTY_VERIFIED_AT,
  GetContract200Response.JSON_PROPERTY_MATCH_ID,
  GetContract200Response.JSON_PROPERTY_CREATION_BYTECODE,
  GetContract200Response.JSON_PROPERTY_RUNTIME_BYTECODE,
  GetContract200Response.JSON_PROPERTY_DEPLOYMENT,
  GetContract200Response.JSON_PROPERTY_SOURCES,
  GetContract200Response.JSON_PROPERTY_COMPILATION,
  GetContract200Response.JSON_PROPERTY_ABI,
  GetContract200Response.JSON_PROPERTY_METADATA,
  GetContract200Response.JSON_PROPERTY_STORAGE_LAYOUT,
  GetContract200Response.JSON_PROPERTY_USERDOC,
  GetContract200Response.JSON_PROPERTY_DEVDOC,
  GetContract200Response.JSON_PROPERTY_SOURCE_IDS,
  GetContract200Response.JSON_PROPERTY_STD_JSON_INPUT,
  GetContract200Response.JSON_PROPERTY_STD_JSON_OUTPUT,
  GetContract200Response.JSON_PROPERTY_PROXY_RESOLUTION
})
@JsonTypeName("get_contract_200_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-08T01:55:37.009934+03:00[Europe/Moscow]", comments = "Generator version: 7.7.0")
public class GetContract200Response {
  /**
   * Gets or Sets match
   */
  public enum MatchEnum {
    MATCH("match"),
    
    EXACT_MATCH("exact_match"),
    
    NULL("null");

    private String value;

    MatchEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static MatchEnum fromValue(String value) {
      for (MatchEnum b : MatchEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_MATCH = "match";
  private MatchEnum match;

  /**
   * Gets or Sets creationMatch
   */
  public enum CreationMatchEnum {
    MATCH("match"),
    
    EXACT_MATCH("exact_match"),
    
    NULL("null");

    private String value;

    CreationMatchEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CreationMatchEnum fromValue(String value) {
      for (CreationMatchEnum b : CreationMatchEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CREATION_MATCH = "creationMatch";
  private CreationMatchEnum creationMatch;

  /**
   * Gets or Sets runtimeMatch
   */
  public enum RuntimeMatchEnum {
    MATCH("match"),
    
    EXACT_MATCH("exact_match"),
    
    NULL("null");

    private String value;

    RuntimeMatchEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RuntimeMatchEnum fromValue(String value) {
      for (RuntimeMatchEnum b : RuntimeMatchEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_RUNTIME_MATCH = "runtimeMatch";
  private RuntimeMatchEnum runtimeMatch;

  public static final String JSON_PROPERTY_CHAIN_ID = "chainId";
  private String chainId;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  private String address;

  public static final String JSON_PROPERTY_VERIFIED_AT = "verifiedAt";
  private OffsetDateTime verifiedAt;

  public static final String JSON_PROPERTY_MATCH_ID = "matchId";
  private String matchId;

  public static final String JSON_PROPERTY_CREATION_BYTECODE = "creationBytecode";
  private CreationBytecodeResponse creationBytecode;

  public static final String JSON_PROPERTY_RUNTIME_BYTECODE = "runtimeBytecode";
  private RuntimeBytecodeResponse runtimeBytecode;

  public static final String JSON_PROPERTY_DEPLOYMENT = "deployment";
  private GetContract200ResponseAllOfDeployment deployment;

  public static final String JSON_PROPERTY_SOURCES = "sources";
  private Map<String, GetContract200ResponseAllOfSourcesValue> sources = new HashMap<>();

  public static final String JSON_PROPERTY_COMPILATION = "compilation";
  private GetContract200ResponseAllOfCompilation compilation;

  public static final String JSON_PROPERTY_ABI = "abi";
  private List<Object> abi = new ArrayList<>();

  public static final String JSON_PROPERTY_METADATA = "metadata";
  private Object metadata;

  public static final String JSON_PROPERTY_STORAGE_LAYOUT = "storageLayout";
  private Object storageLayout;

  public static final String JSON_PROPERTY_USERDOC = "userdoc";
  private Object userdoc;

  public static final String JSON_PROPERTY_DEVDOC = "devdoc";
  private Object devdoc;

  public static final String JSON_PROPERTY_SOURCE_IDS = "sourceIds";
  private Map<String, GetContract200ResponseAllOfSourceIdsValue> sourceIds = new HashMap<>();

  public static final String JSON_PROPERTY_STD_JSON_INPUT = "stdJsonInput";
  private GetContract200ResponseAllOfStdJsonInput stdJsonInput;

  public static final String JSON_PROPERTY_STD_JSON_OUTPUT = "stdJsonOutput";
  private GetContract200ResponseAllOfStdJsonOutput stdJsonOutput;

  public static final String JSON_PROPERTY_PROXY_RESOLUTION = "proxyResolution";
  private ProxyResoltion proxyResolution;

  public GetContract200Response() {
  }

  public GetContract200Response match(MatchEnum match) {
    
    this.match = match;
    return this;
  }

  /**
   * Get match
   * @return match
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MATCH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public MatchEnum getMatch() {
    return match;
  }


  @JsonProperty(JSON_PROPERTY_MATCH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMatch(MatchEnum match) {
    this.match = match;
  }

  public GetContract200Response creationMatch(CreationMatchEnum creationMatch) {
    
    this.creationMatch = creationMatch;
    return this;
  }

  /**
   * Get creationMatch
   * @return creationMatch
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATION_MATCH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CreationMatchEnum getCreationMatch() {
    return creationMatch;
  }


  @JsonProperty(JSON_PROPERTY_CREATION_MATCH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreationMatch(CreationMatchEnum creationMatch) {
    this.creationMatch = creationMatch;
  }

  public GetContract200Response runtimeMatch(RuntimeMatchEnum runtimeMatch) {
    
    this.runtimeMatch = runtimeMatch;
    return this;
  }

  /**
   * Get runtimeMatch
   * @return runtimeMatch
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RUNTIME_MATCH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public RuntimeMatchEnum getRuntimeMatch() {
    return runtimeMatch;
  }


  @JsonProperty(JSON_PROPERTY_RUNTIME_MATCH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRuntimeMatch(RuntimeMatchEnum runtimeMatch) {
    this.runtimeMatch = runtimeMatch;
  }

  public GetContract200Response chainId(String chainId) {
    
    this.chainId = chainId;
    return this;
  }

  /**
   * Get chainId
   * @return chainId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CHAIN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getChainId() {
    return chainId;
  }


  @JsonProperty(JSON_PROPERTY_CHAIN_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setChainId(String chainId) {
    this.chainId = chainId;
  }

  public GetContract200Response address(String address) {
    
    this.address = address;
    return this;
  }

  /**
   * Contract Address in hex string. Can be checksummed or not (i.e. can contain capital letters)
   * @return address
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAddress(String address) {
    this.address = address;
  }

  public GetContract200Response verifiedAt(OffsetDateTime verifiedAt) {
    
    this.verifiedAt = verifiedAt;
    return this;
  }

  /**
   * Get verifiedAt
   * @return verifiedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERIFIED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getVerifiedAt() {
    return verifiedAt;
  }


  @JsonProperty(JSON_PROPERTY_VERIFIED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVerifiedAt(OffsetDateTime verifiedAt) {
    this.verifiedAt = verifiedAt;
  }

  public GetContract200Response matchId(String matchId) {
    
    this.matchId = matchId;
    return this;
  }

  /**
   * Get matchId
   * @return matchId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMatchId() {
    return matchId;
  }


  @JsonProperty(JSON_PROPERTY_MATCH_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMatchId(String matchId) {
    this.matchId = matchId;
  }

  public GetContract200Response creationBytecode(CreationBytecodeResponse creationBytecode) {
    
    this.creationBytecode = creationBytecode;
    return this;
  }

  /**
   * Get creationBytecode
   * @return creationBytecode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATION_BYTECODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CreationBytecodeResponse getCreationBytecode() {
    return creationBytecode;
  }


  @JsonProperty(JSON_PROPERTY_CREATION_BYTECODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreationBytecode(CreationBytecodeResponse creationBytecode) {
    this.creationBytecode = creationBytecode;
  }

  public GetContract200Response runtimeBytecode(RuntimeBytecodeResponse runtimeBytecode) {
    
    this.runtimeBytecode = runtimeBytecode;
    return this;
  }

  /**
   * Get runtimeBytecode
   * @return runtimeBytecode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RUNTIME_BYTECODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RuntimeBytecodeResponse getRuntimeBytecode() {
    return runtimeBytecode;
  }


  @JsonProperty(JSON_PROPERTY_RUNTIME_BYTECODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRuntimeBytecode(RuntimeBytecodeResponse runtimeBytecode) {
    this.runtimeBytecode = runtimeBytecode;
  }

  public GetContract200Response deployment(GetContract200ResponseAllOfDeployment deployment) {
    
    this.deployment = deployment;
    return this;
  }

  /**
   * Get deployment
   * @return deployment
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEPLOYMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetContract200ResponseAllOfDeployment getDeployment() {
    return deployment;
  }


  @JsonProperty(JSON_PROPERTY_DEPLOYMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeployment(GetContract200ResponseAllOfDeployment deployment) {
    this.deployment = deployment;
  }

  public GetContract200Response sources(Map<String, GetContract200ResponseAllOfSourcesValue> sources) {
    
    this.sources = sources;
    return this;
  }

  public GetContract200Response putSourcesItem(String key, GetContract200ResponseAllOfSourcesValue sourcesItem) {
    if (this.sources == null) {
      this.sources = new HashMap<>();
    }
    this.sources.put(key, sourcesItem);
    return this;
  }

  /**
   * Get sources
   * @return sources
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, GetContract200ResponseAllOfSourcesValue> getSources() {
    return sources;
  }


  @JsonProperty(JSON_PROPERTY_SOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSources(Map<String, GetContract200ResponseAllOfSourcesValue> sources) {
    this.sources = sources;
  }

  public GetContract200Response compilation(GetContract200ResponseAllOfCompilation compilation) {
    
    this.compilation = compilation;
    return this;
  }

  /**
   * Get compilation
   * @return compilation
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMPILATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetContract200ResponseAllOfCompilation getCompilation() {
    return compilation;
  }


  @JsonProperty(JSON_PROPERTY_COMPILATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompilation(GetContract200ResponseAllOfCompilation compilation) {
    this.compilation = compilation;
  }

  public GetContract200Response abi(List<Object> abi) {
    
    this.abi = abi;
    return this;
  }

  public GetContract200Response addAbiItem(Object abiItem) {
    if (this.abi == null) {
      this.abi = new ArrayList<>();
    }
    this.abi.add(abiItem);
    return this;
  }

  /**
   * Get abi
   * @return abi
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ABI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getAbi() {
    return abi;
  }


  @JsonProperty(JSON_PROPERTY_ABI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAbi(List<Object> abi) {
    this.abi = abi;
  }

  public GetContract200Response metadata(Object metadata) {
    
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }

  public GetContract200Response storageLayout(Object storageLayout) {
    
    this.storageLayout = storageLayout;
    return this;
  }

  /**
   * Get storageLayout
   * @return storageLayout
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STORAGE_LAYOUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getStorageLayout() {
    return storageLayout;
  }


  @JsonProperty(JSON_PROPERTY_STORAGE_LAYOUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStorageLayout(Object storageLayout) {
    this.storageLayout = storageLayout;
  }

  public GetContract200Response userdoc(Object userdoc) {
    
    this.userdoc = userdoc;
    return this;
  }

  /**
   * Get userdoc
   * @return userdoc
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USERDOC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getUserdoc() {
    return userdoc;
  }


  @JsonProperty(JSON_PROPERTY_USERDOC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserdoc(Object userdoc) {
    this.userdoc = userdoc;
  }

  public GetContract200Response devdoc(Object devdoc) {
    
    this.devdoc = devdoc;
    return this;
  }

  /**
   * Get devdoc
   * @return devdoc
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEVDOC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getDevdoc() {
    return devdoc;
  }


  @JsonProperty(JSON_PROPERTY_DEVDOC)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDevdoc(Object devdoc) {
    this.devdoc = devdoc;
  }

  public GetContract200Response sourceIds(Map<String, GetContract200ResponseAllOfSourceIdsValue> sourceIds) {
    
    this.sourceIds = sourceIds;
    return this;
  }

  public GetContract200Response putSourceIdsItem(String key, GetContract200ResponseAllOfSourceIdsValue sourceIdsItem) {
    if (this.sourceIds == null) {
      this.sourceIds = new HashMap<>();
    }
    this.sourceIds.put(key, sourceIdsItem);
    return this;
  }

  /**
   * Same as stdJsonOutput.sources
   * @return sourceIds
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SOURCE_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, GetContract200ResponseAllOfSourceIdsValue> getSourceIds() {
    return sourceIds;
  }


  @JsonProperty(JSON_PROPERTY_SOURCE_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceIds(Map<String, GetContract200ResponseAllOfSourceIdsValue> sourceIds) {
    this.sourceIds = sourceIds;
  }

  public GetContract200Response stdJsonInput(GetContract200ResponseAllOfStdJsonInput stdJsonInput) {
    
    this.stdJsonInput = stdJsonInput;
    return this;
  }

  /**
   * Get stdJsonInput
   * @return stdJsonInput
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STD_JSON_INPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetContract200ResponseAllOfStdJsonInput getStdJsonInput() {
    return stdJsonInput;
  }


  @JsonProperty(JSON_PROPERTY_STD_JSON_INPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStdJsonInput(GetContract200ResponseAllOfStdJsonInput stdJsonInput) {
    this.stdJsonInput = stdJsonInput;
  }

  public GetContract200Response stdJsonOutput(GetContract200ResponseAllOfStdJsonOutput stdJsonOutput) {
    
    this.stdJsonOutput = stdJsonOutput;
    return this;
  }

  /**
   * Get stdJsonOutput
   * @return stdJsonOutput
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STD_JSON_OUTPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetContract200ResponseAllOfStdJsonOutput getStdJsonOutput() {
    return stdJsonOutput;
  }


  @JsonProperty(JSON_PROPERTY_STD_JSON_OUTPUT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStdJsonOutput(GetContract200ResponseAllOfStdJsonOutput stdJsonOutput) {
    this.stdJsonOutput = stdJsonOutput;
  }

  public GetContract200Response proxyResolution(ProxyResoltion proxyResolution) {
    
    this.proxyResolution = proxyResolution;
    return this;
  }

  /**
   * Get proxyResolution
   * @return proxyResolution
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROXY_RESOLUTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ProxyResoltion getProxyResolution() {
    return proxyResolution;
  }


  @JsonProperty(JSON_PROPERTY_PROXY_RESOLUTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProxyResolution(ProxyResoltion proxyResolution) {
    this.proxyResolution = proxyResolution;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetContract200Response getContract200Response = (GetContract200Response) o;
    return Objects.equals(this.match, getContract200Response.match) &&
        Objects.equals(this.creationMatch, getContract200Response.creationMatch) &&
        Objects.equals(this.runtimeMatch, getContract200Response.runtimeMatch) &&
        Objects.equals(this.chainId, getContract200Response.chainId) &&
        Objects.equals(this.address, getContract200Response.address) &&
        Objects.equals(this.verifiedAt, getContract200Response.verifiedAt) &&
        Objects.equals(this.matchId, getContract200Response.matchId) &&
        Objects.equals(this.creationBytecode, getContract200Response.creationBytecode) &&
        Objects.equals(this.runtimeBytecode, getContract200Response.runtimeBytecode) &&
        Objects.equals(this.deployment, getContract200Response.deployment) &&
        Objects.equals(this.sources, getContract200Response.sources) &&
        Objects.equals(this.compilation, getContract200Response.compilation) &&
        Objects.equals(this.abi, getContract200Response.abi) &&
        Objects.equals(this.metadata, getContract200Response.metadata) &&
        Objects.equals(this.storageLayout, getContract200Response.storageLayout) &&
        Objects.equals(this.userdoc, getContract200Response.userdoc) &&
        Objects.equals(this.devdoc, getContract200Response.devdoc) &&
        Objects.equals(this.sourceIds, getContract200Response.sourceIds) &&
        Objects.equals(this.stdJsonInput, getContract200Response.stdJsonInput) &&
        Objects.equals(this.stdJsonOutput, getContract200Response.stdJsonOutput) &&
        Objects.equals(this.proxyResolution, getContract200Response.proxyResolution);
  }

  @Override
  public int hashCode() {
    return Objects.hash(match, creationMatch, runtimeMatch, chainId, address, verifiedAt, matchId, creationBytecode, runtimeBytecode, deployment, sources, compilation, abi, metadata, storageLayout, userdoc, devdoc, sourceIds, stdJsonInput, stdJsonOutput, proxyResolution);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetContract200Response {\n");
    sb.append("    match: ").append(toIndentedString(match)).append("\n");
    sb.append("    creationMatch: ").append(toIndentedString(creationMatch)).append("\n");
    sb.append("    runtimeMatch: ").append(toIndentedString(runtimeMatch)).append("\n");
    sb.append("    chainId: ").append(toIndentedString(chainId)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    verifiedAt: ").append(toIndentedString(verifiedAt)).append("\n");
    sb.append("    matchId: ").append(toIndentedString(matchId)).append("\n");
    sb.append("    creationBytecode: ").append(toIndentedString(creationBytecode)).append("\n");
    sb.append("    runtimeBytecode: ").append(toIndentedString(runtimeBytecode)).append("\n");
    sb.append("    deployment: ").append(toIndentedString(deployment)).append("\n");
    sb.append("    sources: ").append(toIndentedString(sources)).append("\n");
    sb.append("    compilation: ").append(toIndentedString(compilation)).append("\n");
    sb.append("    abi: ").append(toIndentedString(abi)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    storageLayout: ").append(toIndentedString(storageLayout)).append("\n");
    sb.append("    userdoc: ").append(toIndentedString(userdoc)).append("\n");
    sb.append("    devdoc: ").append(toIndentedString(devdoc)).append("\n");
    sb.append("    sourceIds: ").append(toIndentedString(sourceIds)).append("\n");
    sb.append("    stdJsonInput: ").append(toIndentedString(stdJsonInput)).append("\n");
    sb.append("    stdJsonOutput: ").append(toIndentedString(stdJsonOutput)).append("\n");
    sb.append("    proxyResolution: ").append(toIndentedString(proxyResolution)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

