/*
 * Sourcify APIv2
 * Welcome to the Sourcify's APIv2.  Important differences between the deprecated legacy API and the new APIv2: - **Ticketing**: The verfication requests resolve into tickets/verification jobs.    - Previously the verification happened during the HTTP request, which resulted in timeouts if compilation took longer - **Standard JSON as default**: In the current design we take the standard JSON format as our main verification endpoint. We still support verification with metadata at `/v2/verify/metadata`. - **Lean API**: We keep the number of endpoints minimal compared to v1. We won't have a session API.  - **Detailed contract response**: Prev. we only returned contract files of a contract. Now we can return details at `/contract/{chainId}/{address}`.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: hello@sourcify.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.javaboys.defidog.integrations.sourcify.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.Objects;

/**
 * GetContract200ResponseAllOfStdJsonOutputContractsValueValueEvm
 */
@JsonPropertyOrder({
  GetContract200ResponseAllOfStdJsonOutputContractsValueValueEvm.JSON_PROPERTY_BYTECODE,
  GetContract200ResponseAllOfStdJsonOutputContractsValueValueEvm.JSON_PROPERTY_DEPLOYED_BYTECODE
})
@JsonTypeName("get_contract_200_response_allOf_stdJsonOutput_contracts_value_value_evm")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-08T01:55:37.009934+03:00[Europe/Moscow]", comments = "Generator version: 7.7.0")
public class GetContract200ResponseAllOfStdJsonOutputContractsValueValueEvm {
  public static final String JSON_PROPERTY_BYTECODE = "bytecode";
  private GetContract200ResponseAllOfStdJsonOutputContractsValueValueEvmBytecode bytecode;

  public static final String JSON_PROPERTY_DEPLOYED_BYTECODE = "deployedBytecode";
  private GetContract200ResponseAllOfStdJsonOutputContractsValueValueEvmDeployedBytecode deployedBytecode;

  public GetContract200ResponseAllOfStdJsonOutputContractsValueValueEvm() {
  }

  public GetContract200ResponseAllOfStdJsonOutputContractsValueValueEvm bytecode(GetContract200ResponseAllOfStdJsonOutputContractsValueValueEvmBytecode bytecode) {
    
    this.bytecode = bytecode;
    return this;
  }

  /**
   * Get bytecode
   * @return bytecode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BYTECODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetContract200ResponseAllOfStdJsonOutputContractsValueValueEvmBytecode getBytecode() {
    return bytecode;
  }


  @JsonProperty(JSON_PROPERTY_BYTECODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBytecode(GetContract200ResponseAllOfStdJsonOutputContractsValueValueEvmBytecode bytecode) {
    this.bytecode = bytecode;
  }

  public GetContract200ResponseAllOfStdJsonOutputContractsValueValueEvm deployedBytecode(GetContract200ResponseAllOfStdJsonOutputContractsValueValueEvmDeployedBytecode deployedBytecode) {
    
    this.deployedBytecode = deployedBytecode;
    return this;
  }

  /**
   * Get deployedBytecode
   * @return deployedBytecode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DEPLOYED_BYTECODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public GetContract200ResponseAllOfStdJsonOutputContractsValueValueEvmDeployedBytecode getDeployedBytecode() {
    return deployedBytecode;
  }


  @JsonProperty(JSON_PROPERTY_DEPLOYED_BYTECODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeployedBytecode(GetContract200ResponseAllOfStdJsonOutputContractsValueValueEvmDeployedBytecode deployedBytecode) {
    this.deployedBytecode = deployedBytecode;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetContract200ResponseAllOfStdJsonOutputContractsValueValueEvm getContract200ResponseAllOfStdJsonOutputContractsValueValueEvm = (GetContract200ResponseAllOfStdJsonOutputContractsValueValueEvm) o;
    return Objects.equals(this.bytecode, getContract200ResponseAllOfStdJsonOutputContractsValueValueEvm.bytecode) &&
        Objects.equals(this.deployedBytecode, getContract200ResponseAllOfStdJsonOutputContractsValueValueEvm.deployedBytecode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bytecode, deployedBytecode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetContract200ResponseAllOfStdJsonOutputContractsValueValueEvm {\n");
    sb.append("    bytecode: ").append(toIndentedString(bytecode)).append("\n");
    sb.append("    deployedBytecode: ").append(toIndentedString(deployedBytecode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

